# SPDX-FileCopyrightText: 2019 ash_postgres contributors <https://github.com/ash-project/ash_postgres/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshPostgres.TestRepo.Migrations.KeyedProducts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:keyed_products, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:shop_id, :uuid, null: false)
      add(:sku, :text, null: false)
      add(:barcode, :text)
      add(:serial, :text)
      add(:label, :text)
      add(:handle, :text)
      add(:rank, :bigint)
      add(:stock, :bigint, null: false, default: 0)

      add(
        :owner_id,
        references(:authors,
          column: :id,
          name: "keyed_products_owner_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create(unique_index(:keyed_products, [:handle], name: "keyed_products_unique_handle_index"))

    create(index(:keyed_products, [asc: :shop_id, desc: :sku], unique: true))

    create(index(:keyed_products, ["barcode"], unique: true))

    create(index(:keyed_products, [desc: "serial"], unique: true))

    create(
      index(:keyed_products, ["lower(label)"],
        name: "keyed_products_lower_label_index",
        unique: true
      )
    )

    create(index(:keyed_products, desc: :rank))
  end

  def down do
    drop_if_exists(index(:keyed_products, desc: :rank))

    drop_if_exists(
      index(:keyed_products, ["lower(label)"], name: "keyed_products_lower_label_index")
    )

    drop_if_exists(index(:keyed_products, desc: "serial"))

    drop_if_exists(index(:keyed_products, ["barcode"]))

    drop_if_exists(index(:keyed_products, asc: :shop_id, desc: :sku))

    drop(constraint(:keyed_products, "keyed_products_owner_id_fkey"))

    drop_if_exists(
      unique_index(:keyed_products, [:handle], name: "keyed_products_unique_handle_index")
    )

    drop(table(:keyed_products))
  end
end
